# Generated by Django 3.1.3 on 2020-12-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='si_staff',
            new_name='is_staff',
        ),
    ]
